################
### MONITORS ###
################
monitor = ,preferred, auto, 1, transform, 0

###################
### Permissions ###
###################
permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

###################
### MY PROGRAMS ###
###################
$terminal = kitty
$browser = firefox
$applauncher = tofi-drun
$file_manager = yazi
$editor = nvim

#################
### AUTOSTART ###
#################
exec-once = hyprpolkitagent
exec-once = hypridle
# exec-once = waybar
exec-once = awww-daemon --no-cache
exec-once = clash
exec-once = fcitx5 --replace -d
exec-once = xwayland-satellite
exec-once = battery_capacity.sh
exec-once =	clean_shot.sh
exec-once = clipse -listen
exec-once = wallpaper_switch.sh
# exec-once = gsettings set org.gnome.desktop.interface gtk-theme "Adwaita"

###################
### ENVITONMENT ###
###################
# FCITX5
env = QT_IM_MODULE, fcitx
env = XMODIFIERS=@im, fcitx
env = SDL_IM_MODULE, fcitx

env = XCURSOR_SIZE, 35
env = HYPRCURSOR_SIZE, 35

# BACKEND
env = GDK_BACKEND, wayland
env = QT_QPA_PLATFORM, wayland
env =  MOZ_ENABLE_WAYLAND, 1

# XDG
env = XDG_CURRENT_DESKTOP, Hyprland
env = XDG_SESSION_TYPE, wayland
env = XDG_SEDDION_DESKTOP, Hyprland

# APP
env = BROWSER, $browser
env = EDITOR, $editor
env = TERMINAL, $terminal
env = FILE_MANAGER, $file_manager
env = QT_QPA_PLATFORMTHEME, qt5ct
env = GTK_THEME, Adwaita-dark
# THEME
env = GTK_THEME, Adwaita-dark

### RULE WINDOW
# windowrule = float, class:imv
windowrule = match:class imv, float on
windowrule = match:class mpv, float on
windowrule = match:class zathura, float on
windowrule = match:class QQ, float on
windowrule = match:class wechat, float on
windowrule = match:class org.pwmt.zathura, float on
windowrule = match:class org.kde.kdeconnect.app, float on
windowrule = match:class *QEMU/KVM.*, float on
windowrule = match:class ^Library$, float on
windowrule = match:class (clipse), float on
#
windowrule = match:class imv, center on
windowrule = match:class mpv, center on
windowrule = match:class zathura, center on
windowrule = match:class QQ, center on
windowrule = match:class org.pwmt.zathura, center on
windowrule = match:class *QEMU/KVM.*, center on
windowrule = match:class clipse, center on

windowrule = match:class kitty, opacity 0.99
windowrule = match:class wechat, opacity 0.99
windowrule = match:class firefox, opacity 0.99

windowrule = match:title .*QEMU/KVM.*, size (window_w*0.5) (window_h*0.5)
windowrule = match:class (clipse), size (window_w*0.5) (window_h*0.5)
