# font
font_size 17.0

# srolling back
scrollback_lines 10000
scrollback_pager less --chop-long-lines --RAW-CONTROL-CHARS +INPUT_LINE_NUMBER
scrollback_pager_history_size 500

# mouse trail
cursor_trail 2
cursor_trail_decay 0.1 0.7

# remote control
allow_remote_control yes

# layout
enabled_layouts tall

# window style
hide_window_decorations yes   
window_padding_width 0
remember_window_size yes      
5ackground_opacity 1.0        
background_blur 50            

# tab
tab_bar_edge top               
tab_bar_style powerline        
tab_powerline_style slanted    
tab_title_template "{title}"   
