# clean all default keyboard shortcuts
clear_all_shortcuts yes

# kitty mode prefix
kitty_mod ctrl+shift

# window management
map kitty_mod+p prev_window
map kitty_mod+n next_window
map kitty_mod+o close_other_windows_in_tab
map kitty_mod+x close_window
map kitty_mod+w new_window_with_cwd

# srolling back
map kitty_mod+h show_scrollback

# Misc
map kitty_mod+f5 load_config_file
map kitty_mod+f1 clear_terminal clear active

# copy/paste
map kitty_mod+c copy_to_clipboard
map kitty_mod+v paste_from_clipboard
